//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumDiscount
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public int CountFrom { get; set; }
        public int CountTo { get; set; }
        public double Price { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
