//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool LinkApplicationUser { get; set; }
        public string TemplateUserRegistered { get; set; }
        public string TemplateUserForgotPassword { get; set; }
        public string TemplateProductOrdered { get; set; }
        public string SystemEmailAddress { get; set; }
        public string TemplateUserRegisteredSubject { get; set; }
        public string TemplateUserForgotPasswordSubject { get; set; }
        public string TemplateProductOrderedSubject { get; set; }
    }
}
