//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.UserContracts = new HashSet<UserContract>();
            this.VolumDiscounts = new HashSet<VolumDiscount>();
            this.ContractRecipes = new HashSet<ContractRecipe>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractTypeId { get; set; }
        public string Name { get; set; }
        public bool Advertisement { get; set; }
        public int MaxUris { get; set; }
        public int MaxRedirectsPerUri { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual ICollection<UserContract> UserContracts { get; set; }
        public virtual ICollection<VolumDiscount> VolumDiscounts { get; set; }
        public virtual ICollection<ContractRecipe> ContractRecipes { get; set; }
    }
}
