//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonSettings = new HashSet<PersonSetting>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid Id { get; set; }
        public string NickName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> NationalityId { get; set; }
        public Nullable<System.Guid> GenderId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ICollection<PersonSetting> PersonSettings { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
