//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedirectTypeValue
    {
        public RedirectTypeValue()
        {
            this.UserContractRedirects = new HashSet<UserContractRedirect>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RedirectTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual RedirectType RedirectType { get; set; }
        public virtual ICollection<UserContractRedirect> UserContractRedirects { get; set; }
    }
}
