//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContractRedirect
    {
        public UserContractRedirect()
        {
            this.UserContractLogs = new HashSet<UserContractLog>();
            this.RedirectTypeValues = new HashSet<RedirectTypeValue>();
            this.RuleParameterValues = new HashSet<RuleParameterValue>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserContractUri { get; set; }
        public Nullable<System.DateTime> DateTimeValueStart { get; set; }
        public Nullable<System.DateTime> DateTimeValueStop { get; set; }
        public Nullable<int> DayOfTheWeekValue { get; set; }
        public Nullable<int> TimeOfDayHourStart { get; set; }
        public Nullable<int> TimeOfDayHourEnd { get; set; }
        public Nullable<int> TimeOfDayMinuteStart { get; set; }
        public Nullable<int> TimeOfDayMinuteEnd { get; set; }
        public Nullable<int> Counter { get; set; }
        public string UserAgent { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> UniqueIP { get; set; }
    
        public virtual ICollection<UserContractLog> UserContractLogs { get; set; }
        public virtual Weekday Weekday { get; set; }
        public virtual ICollection<RedirectTypeValue> RedirectTypeValues { get; set; }
        public virtual ICollection<RuleParameterValue> RuleParameterValues { get; set; }
        public virtual UserContractUri UserContractUri1 { get; set; }
    }
}
