//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public System.Guid UserId { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public System.Guid Id { get; set; }
        public bool IsAccountAdmin { get; set; }
        public Nullable<bool> IsReset { get; set; }
        public string EmailAddress { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> CanStatistics { get; set; }
        public Nullable<bool> CanQr { get; set; }
        public Nullable<bool> CanFinance { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    
        public virtual User User { get; set; }
    }
}
