//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContract
    {
        public UserContract()
        {
            this.UserContractLogs = new HashSet<UserContractLog>();
            this.UserContractUris = new HashSet<UserContractUri>();
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.ShoppingBaskets = new HashSet<ShoppingBasket>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Uri { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string TransactionId { get; set; }
        public string eId { get; set; }
        public Nullable<System.Guid> ContractRecipeId { get; set; }
        public Nullable<System.DateTime> LastPaid { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ICollection<UserContractLog> UserContractLogs { get; set; }
        public virtual ICollection<UserContractUri> UserContractUris { get; set; }
        public virtual ContractRecipe ContractRecipe { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<ShoppingBasket> ShoppingBaskets { get; set; }
        public virtual User User { get; set; }
    }
}
