//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tag4sEntities : DbContext
    {
        public Tag4sEntities()
            : base("name=Tag4sEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Nationality> Nationalities { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<PersonSetting> PersonSettings { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Translation> Translations { get; set; }
        public DbSet<TranslationType> TranslationTypes { get; set; }
        public DbSet<MenuChild> MenuChilds { get; set; }
        public DbSet<MenuParent> MenuParents { get; set; }
        public DbSet<TranslationWithType> TranslationWithTypes { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<ContractType> ContractTypes { get; set; }
        public DbSet<RandomUri> RandomUris { get; set; }
        public DbSet<RedirectType> RedirectTypes { get; set; }
        public DbSet<RedirectTypeValue> RedirectTypeValues { get; set; }
        public DbSet<RuleParameter> RuleParameters { get; set; }
        public DbSet<RuleParameterValue> RuleParameterValues { get; set; }
        public DbSet<UserContractLog> UserContractLogs { get; set; }
        public DbSet<UserContractRedirect> UserContractRedirects { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<Weekday> Weekdays { get; set; }
        public DbSet<UserContract> UserContracts { get; set; }
        public DbSet<UserContractUri> UserContractUris { get; set; }
        public DbSet<ContractRecipe> ContractRecipes { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceLine> InvoiceLines { get; set; }
        public DbSet<UserPassword> UserPasswords { get; set; }
        public DbSet<ShoppingBasket> ShoppingBaskets { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<VolumDiscount> VolumDiscounts { get; set; }
        public DbSet<Tooltip> Tooltips { get; set; }
        public DbSet<TooltipWithType> TooltipWithTypes { get; set; }
        public DbSet<Application> Applications { get; set; }
    }
}
