//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationType
    {
        public TranslationType()
        {
            this.Translations = new HashSet<Translation>();
            this.Tooltips = new HashSet<Tooltip>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Translation> Translations { get; set; }
        public virtual ICollection<Tooltip> Tooltips { get; set; }
    }
}
