//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Invoices = new HashSet<Invoice>();
            this.User1 = new HashSet<User>();
            this.UserContracts = new HashSet<UserContract>();
            this.UserPasswords = new HashSet<UserPassword>();
        }
    
        public System.Guid Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string EmailAddress { get; set; }
        public System.Guid UserRoleId { get; set; }
        public Nullable<System.Guid> ReselerId { get; set; }
        public string eId { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string VAT { get; set; }
        public string KVK { get; set; }
        public string Company { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Title { get; set; }
        public string Prefix { get; set; }
        public string Organisation { get; set; }
        public Nullable<bool> DisableEditOwner { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserContract> UserContracts { get; set; }
        public virtual ICollection<UserPassword> UserPasswords { get; set; }
    }
}
