//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContractUri
    {
        public UserContractUri()
        {
            this.RandomUris = new HashSet<RandomUri>();
            this.UserContractLogs = new HashSet<UserContractLog>();
            this.UserContractRedirects = new HashSet<UserContractRedirect>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserContractId { get; set; }
        public string Uri { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public int RandomFunction { get; set; }
    
        public virtual ICollection<RandomUri> RandomUris { get; set; }
        public virtual UserContract UserContract { get; set; }
        public virtual ICollection<UserContractLog> UserContractLogs { get; set; }
        public virtual ICollection<UserContractRedirect> UserContractRedirects { get; set; }
    }
}
