//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tag4s.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContractLog
    {
        public System.Guid Id { get; set; }
        public System.Guid UserContractId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserAgent { get; set; }
        public string Host { get; set; }
        public string ResultUri { get; set; }
        public Nullable<System.Guid> UserContractUri { get; set; }
        public Nullable<System.Guid> UserContractRedirect { get; set; }
    
        public virtual UserContractRedirect UserContractRedirect1 { get; set; }
        public virtual UserContract UserContract { get; set; }
        public virtual UserContractUri UserContractUri1 { get; set; }
    }
}
